export const manager = [
  "",
  "Иванов",
  "Петров",
  "Сидоров",
  "Васичкин",
];

export const medical = [
  "",
  "полный оформляет сам",
  "первичный проходит сам",
  "полный мы оформляем",
  "первичный мы оформляем",
];

export const leader = [
  "",
  "Мхитарян",
  "Назаров",
  "Анисимов",
  "Шарафеев",  
];

export const city = [
  "",
  "Набережные Челны",
  "Уфа",
  "Омск",
  "Хабаровск",  
];

export const verify = [
  "",
  "рекомендую",
  "не рекомендую",
];

export const source = [
  "",
  "авито звонок",
  "турбо",
  "фуры",
  "акция",
  "бывший сотрудник",
  "авито покупка контакта",
  "банеры",
  "автошкола",
  "рассылка уволенным",
  "соцсети",
  "по рекомендации друга",
  "просто дали контакты",
  "авито отклик",
  "сарафанное радио",
  "сайт",
];

export const trailer = [
  "",
  "13",
  "16",
  "13+16",
  "24",
  "17",
  "9",
];

export const area = [
  "",
  "Бурятия",
  "Дагестан",
  "Иркутская обл.",
  "Киргизия",
  "Магнитогорск",
  "Новосиб. обл.",
  "Приморье",
  "Ростовская обл.",
  "Самарская обл.",
  "Свердловская обл.",
  "Омская обл.",
  "Оренбургская обл.",
  "Башкирия",
  "Хабаровский край",
  "Челябинская обл.",
  "Республика Коми",
  "Калининград",
  "Санкт-Петербург",
  "Алтайский край",
  "Красноярский край",
  "Тюменская обл.",
  "Пермский край",
  "Астраханская обл.",
  "Удмуртия",
  "Север",
  "Ульяновск",
  "Уфа",
  "Ижевск",
  "Хабаровск",
  "Наб. Челны",
  "Амурская обл.",
  "Казань",
  "Кемерово",
  "Забайкальск",
  "Мурманская обл.",
  "Москва",
  "Волгоград",
  "Нижний Новгород",
  "Удиуртия",
  "Грозный",
  "Еврейская обл.",
  "Курганская обл.",
  "Краснодар",
  "Саха Якутия",
  "Дальний Восток",
  "Луганская народная респ.",
  "Владимирская обл.",
  "Чувашия",
  "Респ. Алтай",
  "Ставрополь",
  "Барнаул",
  "Подмосковье",
  "Белорусь",
  "Комсомольск-на-Амуре",
  "Благовещенск",
  "Екатеренбург",
  "Респ. Татарстан",
  "Вологодская обл.",
  "Салават",
  "Чистополь",
  "Респ. Хакасия",
  "Улан-Удэ",
  "Чебоксары",
  "Саратов",
  "Тамбовская обл.",
];

export const tableHeader = [
  "№",
  "ФИО",
  "Дата звонка",
  "Менеджер",
  "Телефон",
  "Возраст",
  "Область/Край",
  "Длина прицепа",
  "Стаж на фурах",
  "Источник",
  "ФИО кто привел",
  "Результат СБ",
  "Начальник колонны",
  "Комментарий нач.кол.",
  "Город выхода",
  "Дата выхода",
  "Мед. осмотр",
  "Комментарий ОК",
];

export const register = [
  {
    id: "from",
    label: "Откуда:",
    name: "from-list",
    formId: "form",
    options: [
      {
        value: "все",
        text: "Все",
      },
    ],
  },
  {
    id: "to",
    label: "Получатель:",
    name: "to-list",
    formId: "form",
    options: [
      {
        value: "все",
        text: "Все",
      },
    ],
  },
  {
    id: "status",
    label: "Статус:",
    name: "status-list",
    formId: "form",
    options: [
      {
        value: "все",
        text: "Все",
      },
    ],
  },
];

export const modalContent = [
  {
    id: "name",
    label: "ФИО",
    type: "text",
    name: "fio",
    formId: "modalForm",
    options: [],
  },
  {
    id: "date",
    label: "Дата звонка",
    type: "date",
    name: "date",
    formId: "modalForm",
    options: [],
  },
  {
    id: "manager",
    label: "Менеджер",
    type: "",
    name: "manager",
    formId: "modalForm",
    options: manager.map(item => ({"value": item, "text": item})),
  },
  {
    id: "tel",
    label: "Телефон",
    type: "tel",
    name: "tel",
    formId: "modalForm",
    options: [],
  },
  {
    id: "age",
    label: "Возраст",
    type: "date",
    name: "age",
    formId: "modalForm",
    options: [],
  },
  {
    id: "area",
    label: "Область/Край",
    type: "",
    name: "area",
    formId: "modalForm",
    options: area.map(item => ({"value": item, "text": item})),
  },
  {
    id: "trailer",
    label: "Длина прицепа",
    type: "",
    name: "trailer",
    formId: "modalForm",
    options: trailer.map(item => ({"value": item, "text": item})),
  },
  {
    id: "experience",
    label: "Стаж на фурах",
    type: "number",
    name: "experience",
    formId: "modalForm",
    options: [],
  },
  {
    id: "source",
    label: "Источник",
    type: "source",
    name: "source",
    formId: "modalForm",
    options: source.map(item => ({"value": item, "text": item})),
  },
  {
    id: "advisor",
    label: "ФИО кто привел",
    type: "text",
    name: "advisor",
    formId: "modalForm",
    options: [],
  },
  {
    id: "comment",
    label: "Комментарий",
    type: "text",
    name: "comment",
    formId: "modalForm",
    options: [],
  },
];